In [6]:
import numpy as np
import pandas as pd
from Perceptron import Perceptron


In [7]:
def test_accuracy(model, X_test, y_test):
    i = 0
    for idx, xi in enumerate(X_test):
        if model.predict(xi) != y_test[idx]:
            i+=1

    return i / len(y_test)

In [8]:
attributes = ['variance','skewness','curtosis','entropy','genuine']

df_train = pd.read_csv('../data/bank-note/train.csv', names=attributes)
df_test = pd.read_csv('../data/bank-note/test.csv', names=attributes)

df_train['genuine'].iloc[df_train['genuine'] == 0] = -1
df_test['genuine'].iloc[df_test['genuine'] == 0] = -1

In [9]:
df_test.shape

(500, 5)

In [10]:
X_train = df_train.loc[:, df_train.columns != 'genuine'].to_numpy(dtype='float64')
y_train = df_train['genuine'].to_numpy(dtype='float64')

X_test = df_test.loc[:, df_test.columns != 'genuine'].to_numpy(dtype='float64')
y_test = df_test['genuine'].to_numpy(dtype='float64')

In [11]:
perceptron_standard = Perceptron(X_train, y_train)
perceptron_standard.train_standard(100)

In [12]:
perceptron_standard.w

array([-59.08707378, -36.1626673 , -44.55519523,   2.16733971,
        49.60681493])

In [8]:
perceptron_standard.w

array([-61.086591, -42.70582 , -40.30786 ,  -3.146269,  53.      ])

In [33]:
error_standard = test_accuracy(perceptron_standard, X_test, y_test)
error_standard

0.02

In [34]:
perceptron_standard.w

array([-61.086591, -42.70582 , -40.30786 ,  -3.146269,  53.      ])

In [35]:
perceptron_voted = Perceptron(X_train, y_train)
perceptron_voted.train_voted(1)

In [36]:
error_standard = test_accuracy(perceptron_voted, X_test, y_test)
error_standard

0.014

In [37]:
len(perceptron_voted.w_arr)

259

In [38]:
perceptron_voted.w_arr[-5:]

[(array([-67.451391, -33.35892 , -35.21686 , -13.689772,  54.      ]), 31),
 (array([-65.592991, -41.24492 , -33.55256 , -11.851372,  53.      ]), 82),
 (array([-65.922191, -36.78972 , -38.12436 , -10.862572,  52.      ]), 1),
 (array([-63.891191, -34.93772 , -41.13646 , -10.859569,  53.      ]), 38),
 (array([-61.873491, -33.13952 , -44.09456 , -10.649669,  54.      ]), 55)]

In [39]:
perceptron_avg = Perceptron(X_train, y_train)
perceptron_avg.train_average(1)

In [40]:
error_standard = test_accuracy(perceptron_avg, X_test, y_test)
error_standard

0.014

In [44]:
perceptron_avg.a / perceptron_voted.w_arr[-1][0]

array([6567.56785941, 7648.49268819, 5961.34019072, 7321.87111402,
       5875.03703704])

In [42]:
perceptron_standard.w

array([-61.086591, -42.70582 , -40.30786 ,  -3.146269,  53.      ])