In [1]:
import numpy as np
import pandas as pd
from SVM import SVMClassifier

In [8]:
def test_accuracy(model, X_test, y_test):
    i = 0
    for idx, xi in enumerate(X_test):
        if model.predict(xi) != y_test[idx]:
            i+=1
    return i / len(y_test)

In [3]:
attributes = ['variance','skewness','curtosis','entropy','genuine']

df_train = pd.read_csv('../data/bank-note/train.csv', names=attributes)
df_test = pd.read_csv('../data/bank-note/test.csv', names=attributes)

df_train['genuine'].iloc[df_train['genuine'] == 0] = -1
df_test['genuine'].iloc[df_test['genuine'] == 0] = -1

X_train = df_train.loc[:, df_train.columns != 'genuine'].to_numpy(dtype='float64')
y_train = df_train['genuine'].to_numpy(dtype='float64')

X_test = df_test.loc[:, df_test.columns != 'genuine'].to_numpy(dtype='float64')
y_test = df_test['genuine'].to_numpy(dtype='float64')

C:\Python39\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [4]:
C = [(100/873), (500/873), (700/873)]
alpha = [0.1, 0.5, 1, 2, 5, 10]
lr0 = [0.1, 0.5, 1, 2, 5, 10]

In [5]:
classifier = SVMClassifier(df_train)

In [ ]:
best_error = 100
best_params = {}
for a in alpha:
    for l in lr0:
        errors = []
        for i in range(10):
            classifier.train_primal_ssgd(C[0], l, a)
            errors.append(test_accuracy(classifier, X_test, y_test))
        mean_err = sum(errors) / len(errors)
        if mean_err < best_error:
            best_error = mean_err
            best_params['alpha'] = a
            best_params['lr0'] = l

In [ ]:
best_error = 100

for l in lr0:
    errors = []
    for i in range(10):
        classifier.train_primal_ssgd(C[0], l, alpha=None)
        errors.append(test_accuracy(classifier, X_test, y_test))
    mean_err = sum(errors) / len(errors)
    if mean_err < best_error:
        best_error = mean_err
        best_param = l

In [97]:
best_params

{'alpha': 0.1, 'lr0': 10}

In [120]:
best_param

0.1

In [170]:
classifier.train_primal_ssgd(C[2], 0.1, alpha=None)
classifier.w

array([-18.88804074,  -9.38329448,  -9.7998478 ,  -3.82816754,
        21.06125465])

In [161]:
errors = []
for i in range(10):
    errors.append(test_accuracy(classifier, X_train, y_train))
avg = sum(errors) / len(errors)
avg

0.03440366972477065

In [6]:
classifier_0 = SVMClassifier(df_train)
classifier_0.train_dual(C[0])

classifier_1 = SVMClassifier(df_train)
classifier_1.train_dual(C[1])

classifier_2 = SVMClassifier(df_train)
classifier_2.train_dual(C[2])

In [8]:
classifier_2 = SVMClassifier(df_train)
classifier_2.train_dual(C[2])

In [ ]:
test_accuracy(classifier_2, X_test, y_test)

In [14]:
print(classifier_2.w0)
print(classifier_2.b)
print(classifier_2.w)

[-2.04269191 -1.28026842 -1.51356736 -0.24800877]
5.03764354970973
[-2.04269191 -1.28026842 -1.51356736 -0.24800877  5.03764355]


In [7]:
gammas = [0.1, 0.5, 1, 5, 100]
for gamma in gammas:
    print(gamma)
    print(test_accuracy(classifier_1, X_train, y_train, gamma))

0.1
0.5538990825688074
0.5
0.5538990825688074
1
0.5538990825688074
5
0.5538990825688074
100
0.5538990825688074


In [5]:
gaussian_kernel = lambda xi, xj: np.exp(-1 * (np.sum(np.abs(xi - xj)**2,axis=-1) / gamma))
res = gaussian_kernel(X_train, X_test[0])
res.shape

NameError: name 'gamma' is not defined

In [5]:
classifier_test = SVMClassifier(df_train)
classifier_test.train_dual(C[0])

C:\Python39\lib\site-packages\scipy\optimize\optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "


In [6]:
test_accuracy(classifier_test, X_test, y_test)

0.03

In [5]:
classifier_kernel = SVMClassifier(df_train)
classifier_kernel.train_dual(C[0], 0.5)

In [7]:
classifier_kernel.predict(X_test[0])

(872,)
(872,)
(872, 4)
()


0.0

In [11]:
gammas = [0.1, 0.5, 1, 5, 100]

In [20]:
classifier_kernel1 = SVMClassifier(df_train)
classifier_kernel1.train_dual(C[1], 0.01)
truth_arr1 = classifier_kernel1.alpha > 0.001

classifier_kernel2 = SVMClassifier(df_train)
classifier_kernel2.train_dual(C[1], 0.1)
truth_arr2 = classifier_kernel2.alpha > 0.001

classifier_kernel3 = SVMClassifier(df_train)
classifier_kernel3.train_dual(C[1], 0.5)
truth_arr3 = classifier_kernel3.alpha > 0.001

classifier_kernel4 = SVMClassifier(df_train)
classifier_kernel4.train_dual(C[1], 1)
truth_arr4 = classifier_kernel4.alpha > 0.001

classifier_kernel5 = SVMClassifier(df_train)
classifier_kernel5.train_dual(C[1], 5)
truth_arr5 = classifier_kernel5.alpha > 0.001

classifier_kernel6 = SVMClassifier(df_train)
classifier_kernel6.train_dual(C[1], 100)
truth_arr6 = classifier_kernel6.alpha > 0.001

In [25]:
def find_same_supports(arr1, arr2):
    ctr = 0
    for i, val in enumerate(arr1):
        if val and arr2[i]:
            ctr += 1
    return ctr

In [24]:
truth_arr5.shape

(872,)

In [28]:
print('Support vectors shared when gamma = 0.01 and when gamma = 0.1: %d' % find_same_supports(truth_arr1, truth_arr2))
print('Support vectors shared when gamma = 0.1 and when gamma = 0.5: %d' % find_same_supports(truth_arr2, truth_arr3))
print('Support vectors shared when gamma = 0.5 and when gamma = 1: %d' % find_same_supports(truth_arr3, truth_arr4))
print('Support vectors shared when gamma = 1 and when gamma = 5: %d' % find_same_supports(truth_arr4, truth_arr5))
print('Support vectors shared when gamma = 5 and when gamma = 100: %d' % find_same_supports(truth_arr5, truth_arr6))

Support vectors shared when gamma = 0.01 and when gamma = 0.1: 869
Support vectors shared when gamma = 0.1 and when gamma = 0.5: 730
Support vectors shared when gamma = 0.5 and when gamma = 1: 554
Support vectors shared when gamma = 1 and when gamma = 5: 198
Support vectors shared when gamma = 5 and when gamma = 100: 73


In [19]:
for c in C:
    for gamma in gammas:
        classifier_kernel = SVMClassifier(df_train)
        classifier_kernel.train_dual(c, gamma)
        test_err = test_accuracy(classifier_kernel, X_test, y_test)
        train_err = test_accuracy(classifier_kernel, X_train, y_train)
        print('Training error where C = %f and gammma = %f : %f' % (c, gamma, train_err))   
        print('Testing error where C = %f and gammma = %f : %f' % (c, gamma, test_err))
        print('Number of support vectors %d' % (len(classifier_kernel.nonzero_alphas)))


Training error where C = 0.114548 and gammma = 0.100000 : 0.000000
Testing error where C = 0.114548 and gammma = 0.100000 : 0.002000
Number of support vectors 869
Training error where C = 0.114548 and gammma = 0.500000 : 0.000000
Testing error where C = 0.114548 and gammma = 0.500000 : 0.002000
Number of support vectors 825
Training error where C = 0.114548 and gammma = 1.000000 : 0.000000
Testing error where C = 0.114548 and gammma = 1.000000 : 0.002000
Number of support vectors 804


C:\Python39\lib\site-packages\scipy\optimize\optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "


Training error where C = 0.114548 and gammma = 5.000000 : 0.008028
Testing error where C = 0.114548 and gammma = 5.000000 : 0.006000
Number of support vectors 442
Training error where C = 0.114548 and gammma = 100.000000 : 0.003440
Testing error where C = 0.114548 and gammma = 100.000000 : 0.004000
Number of support vectors 290
Training error where C = 0.572738 and gammma = 0.100000 : 0.000000
Testing error where C = 0.572738 and gammma = 0.100000 : 0.002000
Number of support vectors 869
Training error where C = 0.572738 and gammma = 0.500000 : 0.000000
Testing error where C = 0.572738 and gammma = 0.500000 : 0.002000
Number of support vectors 730
Training error where C = 0.572738 and gammma = 1.000000 : 0.000000
Testing error where C = 0.572738 and gammma = 1.000000 : 0.002000
Number of support vectors 556
Training error where C = 0.572738 and gammma = 5.000000 : 0.000000
Testing error where C = 0.572738 and gammma = 5.000000 : 0.002000
Number of support vectors 208
Training error whe

In [9]:
test_accuracy(classifier_kernel, X_test, y_test)

0.002

In [17]:
mask = classifier_kernel.alpha > 0.001
len(classifier_kernel.alpha[mask])

825

In [21]:
def gaussian_kernel(xi, xj, gamma):
        return np.exp(-np.linalg.norm(xi-xj)**2 / gamma)

In [34]:
sum([gaussian_kernel(xi, X_test[2], 0.5) for xi in X_train]) 

0.0033042888358120522

In [12]:
def gaussian_kernel(xi, xj, gamma):
    return np.exp(-1 * (np.sum(np.abs(xi - xj)**2,axis=-1) / gamma))

In [17]:
def gaussian_kernel_2(xi, xj, gamma):
    return np.exp(-1 * (np.linalg.norm(xi-xj)**2) / gamma)

In [10]:
xi = np.asarray([1,2,3])
xj = np.asarray([3,2,1])
xi @ xj

10

In [19]:
gaussian_kernel_2(xi, xj, 5)

0.20189651799465536